//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotasISPCAN.Commom.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class statusCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal statusCode() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotasISPCAN.Commom.Resources.statusCode", typeof(statusCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        internal static string CategoriaInvalido {
            get {
                return ResourceManager.GetString("CategoriaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 12.
        /// </summary>
        internal static string DescricaoCaractereMinimo11 {
            get {
                return ResourceManager.GetString("DescricaoCaractereMinimo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3.
        /// </summary>
        internal static string DescricaoIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("DescricaoIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7.
        /// </summary>
        internal static string DescricaoNotCaracteresEspecial {
            get {
                return ResourceManager.GetString("DescricaoNotCaracteresEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 19.
        /// </summary>
        internal static string IdAlunoNotNull {
            get {
                return ResourceManager.GetString("IdAlunoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 20.
        /// </summary>
        internal static string IdCadeiraNotNull {
            get {
                return ResourceManager.GetString("IdCadeiraNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 13.
        /// </summary>
        internal static string IdDeveSerInformado {
            get {
                return ResourceManager.GetString("IdDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 14.
        /// </summary>
        internal static string NaoPodeSerApenasNumero {
            get {
                return ResourceManager.GetString("NaoPodeSerApenasNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        internal static string NomeIsNullOrEmpty {
            get {
                return ResourceManager.GetString("NomeIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        internal static string NomeNaoPodeTerLetra {
            get {
                return ResourceManager.GetString("NomeNaoPodeTerLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 18.
        /// </summary>
        internal static string NomeNotCaractereEspecial {
            get {
                return ResourceManager.GetString("NomeNotCaractereEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4.
        /// </summary>
        internal static string Nota1MaiorQue20 {
            get {
                return ResourceManager.GetString("Nota1MaiorQue20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 21.
        /// </summary>
        internal static string Nota1NotNull {
            get {
                return ResourceManager.GetString("Nota1NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        internal static string Nota2MaiorQue20 {
            get {
                return ResourceManager.GetString("Nota2MaiorQue20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22.
        /// </summary>
        internal static string Nota2NotNull {
            get {
                return ResourceManager.GetString("Nota2NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 25.
        /// </summary>
        internal static string NotaInvalid {
            get {
                return ResourceManager.GetString("NotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        internal static string Notamaximo20 {
            get {
                return ResourceManager.GetString("Notamaximo20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 26.
        /// </summary>
        internal static string NotaMenorZero {
            get {
                return ResourceManager.GetString("NotaMenorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 23.
        /// </summary>
        internal static string NotaMinimo {
            get {
                return ResourceManager.GetString("NotaMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9.
        /// </summary>
        internal static string SenhaCaractereMaximo {
            get {
                return ResourceManager.GetString("SenhaCaractereMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        internal static string SenhaCaractereMinimo {
            get {
                return ResourceManager.GetString("SenhaCaractereMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2.
        /// </summary>
        internal static string SenhaIsNullOrEmpty {
            get {
                return ResourceManager.GetString("SenhaIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 16.
        /// </summary>
        internal static string TelefoneCaractereMinimo {
            get {
                return ResourceManager.GetString("TelefoneCaractereMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6.
        /// </summary>
        internal static string TelefoneIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("TelefoneIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 15.
        /// </summary>
        internal static string TokenDeveSerInformado {
            get {
                return ResourceManager.GetString("TokenDeveSerInformado", resourceCulture);
            }
        }
    }
}
